projects:
  newimpactdata-dev:
    schemaPath: src/graphql/schema.json
    includes:
      - graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: angular
        generatedFileName: API.service.ts
        docsFilePath: src/graphql
        region: us-west-2
        apiId: cmu5hisxh5fqxpn2wmqlg74cmi
        maxDepth: 2
extensions:
  amplify:
    version: 3
